---
- name: Installing Nginx and Cronjob configuring it
  hosts: wevservers
  become: true

  tasks:
    - name: Install Nginx
      yum:
        name: nginx
        state: present

    - name: Install Cronjob
      yum:
        name: cronie
        state: present

    - name: Start Nginx
      service:
        name: nginx
        state: started
        enable: true