---
- name: Installing Nginx and Cronjob configuring it
  hosts: webservers
  become: true

  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Install Cronjob
      apt:
        name: cronie
        state: present

    - name: Start Nginx
      service:
        name: nginx
        state: started
        enable: true