---
# tasks file for ec2_launch

- name: Adding SSH access to a security group
  amazon.aws.ec2_group:
    name: aayush-key
    description: Security group for EC2 instances
    region: ap-south-1
    rules:
      - proto: tcp
        from_port: 8080
        to_port: 8080
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0
    rules_egress:
      - proto: all
        cidr_ip: 0.0.0.0/0
  register: security_group
    
- name: Launch Ec2 instance
  amazon.aws.ec2_instance:
    name: Ansible-created-instance
    key_name: aayushvm
    region: ap-south-1
    instance_type: t2.micro
    image_id: ami-0b7207e48d1b6c06f
    count: 1
    security_group: "{{ security_group.group_id }}"
  register: ec2

- name: Wait for instance to be ready
  wait_for:
    host: "{{ ec2.instances[0].public_dns_name }}"
    port: 22
    delay: 30 
    timeout: 300
    state: started
  when: ec2.instances is defined and ec2.instances | length > 0

- name: Add the EC2 instance to the inventory dynamically
  add_host: 
    name: "{{ec2.instances[0].public_dns_name}}"
    groups: dynamic_hosts
    ansible_ssh_private_key_file: "/mnt/c/Users/as699/OneDrive/Desktop/aayu_DevOps/cloud/aayushvm.pem"
    ansible_user: ec2-user

- name: Debug dynamic inventory
  debug: 
    var: groups['dynamic_hosts']

   